import type { DesktopApi, IndexSyncStateEvent, TerminalDataEvent, TerminalSessionInfo, WorkspaceSettingsSection } from "./api";
import type { InvocationActivityEvent, InvocationRecord } from "@exograph/core";

type WorkspaceApi = DesktopApi["workspace"];
type NotesApi = DesktopApi["notes"];
type TerminalsApi = DesktopApi["terminals"];
type ShellApi = DesktopApi["shell"];

export interface DesktopInvokeHandlers {
  "publishing:get-status": DesktopApi["publishing"]["getStatus"];
  "publishing:build": DesktopApi["publishing"]["build"];
  "publishing:stop": DesktopApi["publishing"]["stop"];
  "publishing:reveal-output": DesktopApi["publishing"]["revealOutput"];
  "workspace:get-model": WorkspaceApi["getModel"];
  "workspace:get-settings": WorkspaceApi["getSettings"];
  "workspace:get-setup-state": WorkspaceApi["getSetupState"];
  "workspace:save-onboarding-progress": WorkspaceApi["saveOnboardingProgress"];
  "workspace:reset-onboarding-progress": WorkspaceApi["resetOnboardingProgress"];
  "workspace:mark-onboarding-complete": WorkspaceApi["markOnboardingComplete"];
  "workspace:list-workspaces": WorkspaceApi["listWorkspaces"];
  "workspace:activate-workspace": WorkspaceApi["activateWorkspace"];
  "workspace:save-settings": WorkspaceApi["saveSettings"];
  "workspace:select-folder": WorkspaceApi["selectFolder"];
  "workspace:inspect-content-scope": WorkspaceApi["inspectContentScope"];
  "workspace:get-index-status": WorkspaceApi["getIndexStatus"];
  "workspace:ontology-preview": WorkspaceApi["previewOntology"];
  "workspace:ontology-keep": WorkspaceApi["keepOntology"];
  "workspace:ontology-reject": WorkspaceApi["rejectOntology"];
  "workspace:resolve-preview-target": WorkspaceApi["resolvePreviewTarget"];
  "workspace:read-pdf-file": WorkspaceApi["readPdfFile"];
  "workspace:launch-agent-invocation": WorkspaceApi["launchAgentInvocation"];
  "workspace:get-agent-invocation-authorization": WorkspaceApi["getAgentInvocationAuthorization"];
  "workspace:prepare-graph-maintenance-skill": WorkspaceApi["prepareGraphMaintenanceSkill"];
  "workspace:discover-ontology": WorkspaceApi["discoverOntology"];
  "workspace:get-agent-command-continuity": WorkspaceApi["getAgentCommandContinuity"];
  "workspace:reset-agent-command-continuity": WorkspaceApi["resetAgentCommandContinuity"];
  "workspace:configure-provider-mcp": WorkspaceApi["configureProviderMcp"];
  "workspace:get-cli-installation-status": WorkspaceApi["getCliInstallationStatus"];
  "workspace:install-cli": WorkspaceApi["installCli"];
  "workspace:record-renderer-diagnostic": WorkspaceApi["recordRendererDiagnostic"];
  "workspace:end-agent-invocation": WorkspaceApi["endAgentInvocation"];
  "workspace:list-pending-invocation-reviews": WorkspaceApi["listPendingInvocationReviews"];
  "workspace:list-invocation-history": WorkspaceApi["listInvocationHistory"];
  "workspace:get-invocation-file-review": WorkspaceApi["getInvocationFileReview"];
  "workspace:review-invocation-file": WorkspaceApi["reviewInvocationFile"];
  "workspace:review-invocation-all": WorkspaceApi["reviewInvocationAll"];
  "workspace:resume-invocation-in-terminal": WorkspaceApi["resumeInvocationInTerminal"];
  "workspace:index-sync": WorkspaceApi["syncIndex"];
  "workspace:index-update": WorkspaceApi["updateIndex"];
  "workspace:index-embed": WorkspaceApi["embedIndex"];
  "workspace:list-tree": WorkspaceApi["listTree"];
  "workspace:search-workspace": WorkspaceApi["searchWorkspace"];
  "workspace:search-index": WorkspaceApi["searchIndex"];
  "workspace:search-tag": WorkspaceApi["searchTag"];
  "workspace:get-folder-overview": WorkspaceApi["getFolderOverview"];
  "workspace:ensure-folder-index": WorkspaceApi["ensureFolderIndex"];
  "workspace:create-file": WorkspaceApi["createFile"];
  "workspace:create-folder": WorkspaceApi["createFolder"];
  "workspace:rename-path": WorkspaceApi["renamePath"];
  "workspace:delete-path": WorkspaceApi["deletePath"];
  "notes:read": NotesApi["read"];
  "notes:save": NotesApi["save"];
  "notes:save-copy": NotesApi["saveCopy"];
  "notes:stat": NotesApi["stat"];
  "notes:get-graph-context": NotesApi["getGraphContext"];
  "notes:get-graph-topology": NotesApi["getGraphTopology"];
  "notes:get-graph-concept-summaries": NotesApi["getGraphConceptSummaries"];
  "notes:graph-concept-lookup": NotesApi["graphConceptLookup"];
  "notes:get-graph-concept-detail-by-index": NotesApi["getGraphConceptDetailByIndex"];
  "notes:resolve-target": NotesApi["resolveTarget"];
  "notes:resolve-markdown-image": NotesApi["resolveMarkdownImage"];
  "notes:ensure-target": NotesApi["ensureTarget"];
  "notes:suggest-targets": NotesApi["suggestTargets"];
  "terminals:list": TerminalsApi["list"];
  "terminals:create": TerminalsApi["create"];
  "terminals:read": TerminalsApi["read"];
  "terminals:write": TerminalsApi["write"];
  "terminals:send-message": TerminalsApi["sendMessage"];
  "terminals:resize": TerminalsApi["resize"];
  "terminals:kill": TerminalsApi["kill"];
  "shell:open-external": ShellApi["openExternal"];
  "shell:focus-window": ShellApi["focusWindow"];
  "shell:change-zoom": ShellApi["changeZoom"];
}

export interface DesktopEventPayloads {
  "publishing:status": Awaited<ReturnType<DesktopApi["publishing"]["getStatus"]>>;
  "workspace:changed": { rootPath: string; eventType: string; filePath: string | null };
  "workspace:index-sync-state": IndexSyncStateEvent;
  "workspace:graph-changed": { source: "ontology" };
  "workspace:ontology-candidate-changed": undefined;
  "workspace:invocation-updated": InvocationRecord;
  "workspace:invocation-activity": InvocationActivityEvent;
  "command:open-file": string;
  "command:open-settings": { section: WorkspaceSettingsSection };
  "terminal:created": TerminalSessionInfo;
  "terminal:data": TerminalDataEvent;
  "terminal:exit": { id: string; exitCode?: number };
}

export type DesktopInvokeChannel = keyof DesktopInvokeHandlers;
export type DesktopEventChannel = keyof DesktopEventPayloads;
